server:
    port: 8080
    context-path: /

spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_user
      username: root
      password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

person:
  age: 11
  lists:
    -1
    -2
  dog:
    age: ${random.int}
    name: ${random.uuid}dog
  name: guow

#spring:
#  profiles:
#    active: dev

---
server:
  port: 8083
spring:
  profiles: dev

---
server:
  port: 8084
spring:
  profiles: prod